// Generated by gencpp from file panthera_locomotion/custom_msg.msg
// DO NOT EDIT!


#ifndef PANTHERA_LOCOMOTION_MESSAGE_CUSTOM_MSG_H
#define PANTHERA_LOCOMOTION_MESSAGE_CUSTOM_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace panthera_locomotion
{
template <class ContainerAllocator>
struct custom_msg_
{
  typedef custom_msg_<ContainerAllocator> Type;

  custom_msg_()
    : current(0.0)
    , speed(0.0)  {
    }
  custom_msg_(const ContainerAllocator& _alloc)
    : current(0.0)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef double _current_type;
  _current_type current;

   typedef double _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::panthera_locomotion::custom_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::panthera_locomotion::custom_msg_<ContainerAllocator> const> ConstPtr;

}; // struct custom_msg_

typedef ::panthera_locomotion::custom_msg_<std::allocator<void> > custom_msg;

typedef boost::shared_ptr< ::panthera_locomotion::custom_msg > custom_msgPtr;
typedef boost::shared_ptr< ::panthera_locomotion::custom_msg const> custom_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::panthera_locomotion::custom_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::panthera_locomotion::custom_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::panthera_locomotion::custom_msg_<ContainerAllocator1> & lhs, const ::panthera_locomotion::custom_msg_<ContainerAllocator2> & rhs)
{
  return lhs.current == rhs.current &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::panthera_locomotion::custom_msg_<ContainerAllocator1> & lhs, const ::panthera_locomotion::custom_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace panthera_locomotion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::panthera_locomotion::custom_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panthera_locomotion::custom_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panthera_locomotion::custom_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panthera_locomotion::custom_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panthera_locomotion::custom_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panthera_locomotion::custom_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::panthera_locomotion::custom_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d536eea85ef9bde96bb2e6eec26a59a2";
  }

  static const char* value(const ::panthera_locomotion::custom_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd536eea85ef9bde9ULL;
  static const uint64_t static_value2 = 0x6bb2e6eec26a59a2ULL;
};

template<class ContainerAllocator>
struct DataType< ::panthera_locomotion::custom_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panthera_locomotion/custom_msg";
  }

  static const char* value(const ::panthera_locomotion::custom_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::panthera_locomotion::custom_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 current\n"
"float64 speed\n"
;
  }

  static const char* value(const ::panthera_locomotion::custom_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::panthera_locomotion::custom_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct custom_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::panthera_locomotion::custom_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::panthera_locomotion::custom_msg_<ContainerAllocator>& v)
  {
    s << indent << "current: ";
    Printer<double>::stream(s, indent + "  ", v.current);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANTHERA_LOCOMOTION_MESSAGE_CUSTOM_MSG_H
