// Generated by gencpp from file panthera_locomotion/ICRsearchRequest.msg
// DO NOT EDIT!


#ifndef PANTHERA_LOCOMOTION_MESSAGE_ICRSEARCHREQUEST_H
#define PANTHERA_LOCOMOTION_MESSAGE_ICRSEARCHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace panthera_locomotion
{
template <class ContainerAllocator>
struct ICRsearchRequest_
{
  typedef ICRsearchRequest_<ContainerAllocator> Type;

  ICRsearchRequest_()
    : received_angle(false)
    , turn_angle(0.0)  {
    }
  ICRsearchRequest_(const ContainerAllocator& _alloc)
    : received_angle(false)
    , turn_angle(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _received_angle_type;
  _received_angle_type received_angle;

   typedef double _turn_angle_type;
  _turn_angle_type turn_angle;





  typedef boost::shared_ptr< ::panthera_locomotion::ICRsearchRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::panthera_locomotion::ICRsearchRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ICRsearchRequest_

typedef ::panthera_locomotion::ICRsearchRequest_<std::allocator<void> > ICRsearchRequest;

typedef boost::shared_ptr< ::panthera_locomotion::ICRsearchRequest > ICRsearchRequestPtr;
typedef boost::shared_ptr< ::panthera_locomotion::ICRsearchRequest const> ICRsearchRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::panthera_locomotion::ICRsearchRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::panthera_locomotion::ICRsearchRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::panthera_locomotion::ICRsearchRequest_<ContainerAllocator1> & lhs, const ::panthera_locomotion::ICRsearchRequest_<ContainerAllocator2> & rhs)
{
  return lhs.received_angle == rhs.received_angle &&
    lhs.turn_angle == rhs.turn_angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::panthera_locomotion::ICRsearchRequest_<ContainerAllocator1> & lhs, const ::panthera_locomotion::ICRsearchRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace panthera_locomotion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::panthera_locomotion::ICRsearchRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panthera_locomotion::ICRsearchRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panthera_locomotion::ICRsearchRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panthera_locomotion::ICRsearchRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panthera_locomotion::ICRsearchRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panthera_locomotion::ICRsearchRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::panthera_locomotion::ICRsearchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b0f9d7b5541dc5d4d54f360e0b450a0";
  }

  static const char* value(const ::panthera_locomotion::ICRsearchRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b0f9d7b5541dc5dULL;
  static const uint64_t static_value2 = 0x4d54f360e0b450a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::panthera_locomotion::ICRsearchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panthera_locomotion/ICRsearchRequest";
  }

  static const char* value(const ::panthera_locomotion::ICRsearchRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::panthera_locomotion::ICRsearchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool received_angle\n"
"float64 turn_angle\n"
;
  }

  static const char* value(const ::panthera_locomotion::ICRsearchRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::panthera_locomotion::ICRsearchRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.received_angle);
      stream.next(m.turn_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ICRsearchRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::panthera_locomotion::ICRsearchRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::panthera_locomotion::ICRsearchRequest_<ContainerAllocator>& v)
  {
    s << indent << "received_angle: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.received_angle);
    s << indent << "turn_angle: ";
    Printer<double>::stream(s, indent + "  ", v.turn_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANTHERA_LOCOMOTION_MESSAGE_ICRSEARCHREQUEST_H
