// Generated by gencpp from file panthera_locomotion/ICRsearch.msg
// DO NOT EDIT!


#ifndef PANTHERA_LOCOMOTION_MESSAGE_ICRSEARCH_H
#define PANTHERA_LOCOMOTION_MESSAGE_ICRSEARCH_H

#include <ros/service_traits.h>


#include <panthera_locomotion/ICRsearchRequest.h>
#include <panthera_locomotion/ICRsearchResponse.h>


namespace panthera_locomotion
{

struct ICRsearch
{

typedef ICRsearchRequest Request;
typedef ICRsearchResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ICRsearch
} // namespace panthera_locomotion


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::panthera_locomotion::ICRsearch > {
  static const char* value()
  {
    return "bcaf6636f1df5330595534eeebecd7f8";
  }

  static const char* value(const ::panthera_locomotion::ICRsearch&) { return value(); }
};

template<>
struct DataType< ::panthera_locomotion::ICRsearch > {
  static const char* value()
  {
    return "panthera_locomotion/ICRsearch";
  }

  static const char* value(const ::panthera_locomotion::ICRsearch&) { return value(); }
};


// service_traits::MD5Sum< ::panthera_locomotion::ICRsearchRequest> should match
// service_traits::MD5Sum< ::panthera_locomotion::ICRsearch >
template<>
struct MD5Sum< ::panthera_locomotion::ICRsearchRequest>
{
  static const char* value()
  {
    return MD5Sum< ::panthera_locomotion::ICRsearch >::value();
  }
  static const char* value(const ::panthera_locomotion::ICRsearchRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::panthera_locomotion::ICRsearchRequest> should match
// service_traits::DataType< ::panthera_locomotion::ICRsearch >
template<>
struct DataType< ::panthera_locomotion::ICRsearchRequest>
{
  static const char* value()
  {
    return DataType< ::panthera_locomotion::ICRsearch >::value();
  }
  static const char* value(const ::panthera_locomotion::ICRsearchRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::panthera_locomotion::ICRsearchResponse> should match
// service_traits::MD5Sum< ::panthera_locomotion::ICRsearch >
template<>
struct MD5Sum< ::panthera_locomotion::ICRsearchResponse>
{
  static const char* value()
  {
    return MD5Sum< ::panthera_locomotion::ICRsearch >::value();
  }
  static const char* value(const ::panthera_locomotion::ICRsearchResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::panthera_locomotion::ICRsearchResponse> should match
// service_traits::DataType< ::panthera_locomotion::ICRsearch >
template<>
struct DataType< ::panthera_locomotion::ICRsearchResponse>
{
  static const char* value()
  {
    return DataType< ::panthera_locomotion::ICRsearch >::value();
  }
  static const char* value(const ::panthera_locomotion::ICRsearchResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PANTHERA_LOCOMOTION_MESSAGE_ICRSEARCH_H
