// Generated by gencpp from file panthera_locomotion/Status.msg
// DO NOT EDIT!


#ifndef PANTHERA_LOCOMOTION_MESSAGE_STATUS_H
#define PANTHERA_LOCOMOTION_MESSAGE_STATUS_H

#include <ros/service_traits.h>


#include <panthera_locomotion/StatusRequest.h>
#include <panthera_locomotion/StatusResponse.h>


namespace panthera_locomotion
{

struct Status
{

typedef StatusRequest Request;
typedef StatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Status
} // namespace panthera_locomotion


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::panthera_locomotion::Status > {
  static const char* value()
  {
    return "6eac67a75eb7db125401139ae8ae1357";
  }

  static const char* value(const ::panthera_locomotion::Status&) { return value(); }
};

template<>
struct DataType< ::panthera_locomotion::Status > {
  static const char* value()
  {
    return "panthera_locomotion/Status";
  }

  static const char* value(const ::panthera_locomotion::Status&) { return value(); }
};


// service_traits::MD5Sum< ::panthera_locomotion::StatusRequest> should match
// service_traits::MD5Sum< ::panthera_locomotion::Status >
template<>
struct MD5Sum< ::panthera_locomotion::StatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::panthera_locomotion::Status >::value();
  }
  static const char* value(const ::panthera_locomotion::StatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::panthera_locomotion::StatusRequest> should match
// service_traits::DataType< ::panthera_locomotion::Status >
template<>
struct DataType< ::panthera_locomotion::StatusRequest>
{
  static const char* value()
  {
    return DataType< ::panthera_locomotion::Status >::value();
  }
  static const char* value(const ::panthera_locomotion::StatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::panthera_locomotion::StatusResponse> should match
// service_traits::MD5Sum< ::panthera_locomotion::Status >
template<>
struct MD5Sum< ::panthera_locomotion::StatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::panthera_locomotion::Status >::value();
  }
  static const char* value(const ::panthera_locomotion::StatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::panthera_locomotion::StatusResponse> should match
// service_traits::DataType< ::panthera_locomotion::Status >
template<>
struct DataType< ::panthera_locomotion::StatusResponse>
{
  static const char* value()
  {
    return DataType< ::panthera_locomotion::Status >::value();
  }
  static const char* value(const ::panthera_locomotion::StatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PANTHERA_LOCOMOTION_MESSAGE_STATUS_H
