// Generated by gencpp from file panthera_locomotion/StatusRequest.msg
// DO NOT EDIT!


#ifndef PANTHERA_LOCOMOTION_MESSAGE_STATUSREQUEST_H
#define PANTHERA_LOCOMOTION_MESSAGE_STATUSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace panthera_locomotion
{
template <class ContainerAllocator>
struct StatusRequest_
{
  typedef StatusRequest_<ContainerAllocator> Type;

  StatusRequest_()
    : reconfig(false)  {
    }
  StatusRequest_(const ContainerAllocator& _alloc)
    : reconfig(false)  {
  (void)_alloc;
    }



   typedef uint8_t _reconfig_type;
  _reconfig_type reconfig;





  typedef boost::shared_ptr< ::panthera_locomotion::StatusRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::panthera_locomotion::StatusRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StatusRequest_

typedef ::panthera_locomotion::StatusRequest_<std::allocator<void> > StatusRequest;

typedef boost::shared_ptr< ::panthera_locomotion::StatusRequest > StatusRequestPtr;
typedef boost::shared_ptr< ::panthera_locomotion::StatusRequest const> StatusRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::panthera_locomotion::StatusRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::panthera_locomotion::StatusRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::panthera_locomotion::StatusRequest_<ContainerAllocator1> & lhs, const ::panthera_locomotion::StatusRequest_<ContainerAllocator2> & rhs)
{
  return lhs.reconfig == rhs.reconfig;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::panthera_locomotion::StatusRequest_<ContainerAllocator1> & lhs, const ::panthera_locomotion::StatusRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace panthera_locomotion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::panthera_locomotion::StatusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panthera_locomotion::StatusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panthera_locomotion::StatusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panthera_locomotion::StatusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panthera_locomotion::StatusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panthera_locomotion::StatusRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::panthera_locomotion::StatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cdc35faafd94fe7d4c46256ad525db4d";
  }

  static const char* value(const ::panthera_locomotion::StatusRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcdc35faafd94fe7dULL;
  static const uint64_t static_value2 = 0x4c46256ad525db4dULL;
};

template<class ContainerAllocator>
struct DataType< ::panthera_locomotion::StatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panthera_locomotion/StatusRequest";
  }

  static const char* value(const ::panthera_locomotion::StatusRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::panthera_locomotion::StatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool reconfig\n"
;
  }

  static const char* value(const ::panthera_locomotion::StatusRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::panthera_locomotion::StatusRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reconfig);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StatusRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::panthera_locomotion::StatusRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::panthera_locomotion::StatusRequest_<ContainerAllocator>& v)
  {
    s << indent << "reconfig: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reconfig);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANTHERA_LOCOMOTION_MESSAGE_STATUSREQUEST_H
