# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from local_planner/CmapClear.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CmapClear(genpy.Message):
  _md5sum = "fcdcf2c8de4d9bb6062a42facde1b732"
  _type = "local_planner/CmapClear"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool right
bool up
bool left
bool back
bool radius
"""
  __slots__ = ['right','up','left','back','radius']
  _slot_types = ['bool','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       right,up,left,back,radius

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CmapClear, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.right is None:
        self.right = False
      if self.up is None:
        self.up = False
      if self.left is None:
        self.left = False
      if self.back is None:
        self.back = False
      if self.radius is None:
        self.radius = False
    else:
      self.right = False
      self.up = False
      self.left = False
      self.back = False
      self.radius = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5B().pack(_x.right, _x.up, _x.left, _x.back, _x.radius))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.right, _x.up, _x.left, _x.back, _x.radius,) = _get_struct_5B().unpack(str[start:end])
      self.right = bool(self.right)
      self.up = bool(self.up)
      self.left = bool(self.left)
      self.back = bool(self.back)
      self.radius = bool(self.radius)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5B().pack(_x.right, _x.up, _x.left, _x.back, _x.radius))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.right, _x.up, _x.left, _x.back, _x.radius,) = _get_struct_5B().unpack(str[start:end])
      self.right = bool(self.right)
      self.up = bool(self.up)
      self.left = bool(self.left)
      self.back = bool(self.back)
      self.radius = bool(self.radius)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5B = None
def _get_struct_5B():
    global _struct_5B
    if _struct_5B is None:
        _struct_5B = struct.Struct("<5B")
    return _struct_5B
