// Generated by gencpp from file local_planner/CmapClear.msg
// DO NOT EDIT!


#ifndef LOCAL_PLANNER_MESSAGE_CMAPCLEAR_H
#define LOCAL_PLANNER_MESSAGE_CMAPCLEAR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace local_planner
{
template <class ContainerAllocator>
struct CmapClear_
{
  typedef CmapClear_<ContainerAllocator> Type;

  CmapClear_()
    : right(false)
    , up(false)
    , left(false)
    , back(false)
    , radius(false)  {
    }
  CmapClear_(const ContainerAllocator& _alloc)
    : right(false)
    , up(false)
    , left(false)
    , back(false)
    , radius(false)  {
  (void)_alloc;
    }



   typedef uint8_t _right_type;
  _right_type right;

   typedef uint8_t _up_type;
  _up_type up;

   typedef uint8_t _left_type;
  _left_type left;

   typedef uint8_t _back_type;
  _back_type back;

   typedef uint8_t _radius_type;
  _radius_type radius;





  typedef boost::shared_ptr< ::local_planner::CmapClear_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::local_planner::CmapClear_<ContainerAllocator> const> ConstPtr;

}; // struct CmapClear_

typedef ::local_planner::CmapClear_<std::allocator<void> > CmapClear;

typedef boost::shared_ptr< ::local_planner::CmapClear > CmapClearPtr;
typedef boost::shared_ptr< ::local_planner::CmapClear const> CmapClearConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::local_planner::CmapClear_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::local_planner::CmapClear_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::local_planner::CmapClear_<ContainerAllocator1> & lhs, const ::local_planner::CmapClear_<ContainerAllocator2> & rhs)
{
  return lhs.right == rhs.right &&
    lhs.up == rhs.up &&
    lhs.left == rhs.left &&
    lhs.back == rhs.back &&
    lhs.radius == rhs.radius;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::local_planner::CmapClear_<ContainerAllocator1> & lhs, const ::local_planner::CmapClear_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace local_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::local_planner::CmapClear_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::local_planner::CmapClear_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::local_planner::CmapClear_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::local_planner::CmapClear_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::local_planner::CmapClear_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::local_planner::CmapClear_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::local_planner::CmapClear_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fcdcf2c8de4d9bb6062a42facde1b732";
  }

  static const char* value(const ::local_planner::CmapClear_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfcdcf2c8de4d9bb6ULL;
  static const uint64_t static_value2 = 0x062a42facde1b732ULL;
};

template<class ContainerAllocator>
struct DataType< ::local_planner::CmapClear_<ContainerAllocator> >
{
  static const char* value()
  {
    return "local_planner/CmapClear";
  }

  static const char* value(const ::local_planner::CmapClear_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::local_planner::CmapClear_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool right\n"
"bool up\n"
"bool left\n"
"bool back\n"
"bool radius\n"
;
  }

  static const char* value(const ::local_planner::CmapClear_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::local_planner::CmapClear_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.right);
      stream.next(m.up);
      stream.next(m.left);
      stream.next(m.back);
      stream.next(m.radius);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CmapClear_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::local_planner::CmapClear_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::local_planner::CmapClear_<ContainerAllocator>& v)
  {
    s << indent << "right: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right);
    s << indent << "up: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.up);
    s << indent << "left: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left);
    s << indent << "back: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.back);
    s << indent << "radius: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.radius);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCAL_PLANNER_MESSAGE_CMAPCLEAR_H
